import { mkdir, writeFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join, resolve } from 'path';
import chalk from 'chalk';
import ora from 'ora';

/**
 * Create a new MCP server project
 * @param {string} name - Project name
 * @param {object} options - CLI options
 */
export async function createProject(name, options = {}) {
  const dir = options.directory ? resolve(options.directory) : resolve(process.cwd(), name);

  if (existsSync(dir)) {
    throw new Error(`Directory "${dir}" already exists.`);
  }

  const hasHttp = options.http || options.all;
  const hasStdio = !options.http || options.all;

  const spinner = ora(`Creating MCP server project "${name}"...`).start();

  try {
    // Create project directory
    await mkdir(dir, { recursive: true });

    // package.json
    const pkgJson = generatePackageJson(name, hasHttp);
    await writeFile(join(dir, 'package.json'), JSON.stringify(pkgJson, null, 2) + '\n');
    spinner.text = 'Created package.json';

    // index.js - main server
    const indexJs = generateIndexJs(name, hasHttp, hasStdio);
    await writeFile(join(dir, 'index.js'), indexJs);
    spinner.text = 'Created index.js';

    // README.md
    const readme = generateReadme(name, hasHttp, hasStdio);
    await writeFile(join(dir, 'README.md'), readme);
    spinner.text = 'Created README.md';

    // .env.example
    const envExample = generateEnvExample(hasHttp);
    await writeFile(join(dir, '.env.example'), envExample);
    spinner.text = 'Created .env.example';

    // .gitignore
    await writeFile(join(dir, '.gitignore'), 'node_modules/\n.env\ndist/\n');
    spinner.text = 'Created .gitignore';

    spinner.succeed(chalk.green(`MCP server project "${name}" created successfully!`));

    console.log(`\n  ${chalk.bold('Next steps:')}`);
    console.log(`    cd ${name}`);
    console.log(`    npm install`);
    console.log(`    npm start\n`);

    if (hasHttp) {
      console.log(`  ${chalk.bold('HTTP transport enabled:')}`);
      console.log(`    Copy .env.example to .env and configure your settings\n`);
    }
  } catch (err) {
    spinner.fail(chalk.red('Failed to create project'));
    throw err;
  }
}

function generatePackageJson(name, hasHttp) {
  const pkg = {
    name,
    version: '1.0.0',
    description: `MCP server generated by scl339-mcp-server`,
    main: 'index.js',
    type: 'module',
    scripts: {
      start: 'node index.js',
      dev: 'node --watch index.js',
    },
    keywords: ['mcp', 'model-context-protocol', 'ai-agents'],
    license: 'MIT',
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.0.0',
    },
  };

  if (hasHttp) {
    pkg.dependencies.express = '^4.18.0';
    pkg.dependencies.cors = '^2.8.5';
  }

  return pkg;
}

function generateIndexJs(name, hasHttp, hasStdio) {
  let code = `/**
 * MCP Server: ${name}
 * Generated by scl339-mcp-server
 * 
 * This is an MCP (Model Context Protocol) server that provides
 * tools and resources to AI coding assistants.
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ListResourcesRequestSchema,
  ReadResourceRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

`;

  if (hasHttp) {
    code += `import express from 'express';
import cors from 'cors';
import { createServer } from 'http';

`;
  }

  code += `// ---------------------------------------------------------------------------
// Tool Definitions
// ---------------------------------------------------------------------------

const TOOLS = [
  {
    name: 'hello',
    description: 'A simple hello world tool',
    inputSchema: {
      type: 'object',
      properties: {
        name: { type: 'string', description: 'Your name' },
      },
      required: ['name'],
    },
  },
  {
    name: 'echo',
    description: 'Echo back the input message',
    inputSchema: {
      type: 'object',
      properties: {
        message: { type: 'string', description: 'Message to echo' },
      },
      required: ['message'],
    },
  },
];

// ---------------------------------------------------------------------------
// Resource Definitions
// ---------------------------------------------------------------------------

const RESOURCES = [
  {
    uri: 'mcp://info',
    name: 'Server Info',
    description: 'Information about this MCP server',
    mimeType: 'application/json',
  },
];

// ---------------------------------------------------------------------------
// Create MCP Server
// ---------------------------------------------------------------------------

const server = new Server(
  {
    name: '${name}',
    version: '1.0.0',
  },
  {
    capabilities: {
      tools: {},
      resources: {},
    },
  },
);

// Handle tool listing
server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: TOOLS,
}));

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  switch (name) {
    case 'hello': {
      return {
        content: [{ type: 'text', text: \`Hello, \${args.name || 'World'}! Welcome to MCP.\` }],
      };
    }
    case 'echo': {
      return {
        content: [{ type: 'text', text: args.message || '' }],
      };
    }
    default:
      throw new Error(\`Unknown tool: \${name}\`);
  }
});

// Handle resource listing
server.setRequestHandler(ListResourcesRequestSchema, async () => ({
  resources: RESOURCES,
}));

// Handle resource reading
server.setRequestHandler(ReadResourceRequestSchema, async (request) => {
  const uri = request.params.uri;

  switch (uri) {
    case 'mcp://info': {
      return {
        contents: [
          {
            uri,
            mimeType: 'application/json',
            text: JSON.stringify({ name: '${name}', version: '1.0.0', node: process.version }, null, 2),
          },
        ],
      };
    }
    default:
      throw new Error(\`Unknown resource: \${uri}\`);
  }
});

// ---------------------------------------------------------------------------
// Start Server
// ---------------------------------------------------------------------------

async function main() {
`;

  if (hasStdio && hasHttp) {
    code += `  // Start stdio transport
  const stdioTransport = new StdioServerTransport();
  await server.connect(stdioTransport);
  console.error('MCP server running on stdio');

  // Start HTTP transport
  const app = express();
  app.use(cors());
  app.use(express.json());

  app.post('/mcp', async (req, res) => {
    try {
      const { method, params, id } = req.body;
      const result = await server.requestHandler({ method, params });
      res.json({ jsonrpc: '2.0', result, id });
    } catch (err) {
      res.status(500).json({ jsonrpc: '2.0', error: { message: err.message }, id: req.body.id });
    }
  });

  app.get('/health', (_req, res) => res.json({ status: 'ok', server: '${name}' }));

  const PORT = process.env.PORT || 3000;
  const httpServer = createServer(app);
  httpServer.listen(PORT, () => {
    console.error(\`MCP HTTP server listening on port \${PORT}\`);
  });
`;
  } else if (hasHttp) {
    code += `  const app = express();
  app.use(cors());
  app.use(express.json());

  app.post('/mcp', async (req, res) => {
    try {
      const { method, params, id } = req.body;
      const result = await server.requestHandler({ method, params });
      res.json({ jsonrpc: '2.0', result, id });
    } catch (err) {
      res.status(500).json({ jsonrpc: '2.0', error: { message: err.message }, id: req.body.id });
    }
  });

  app.get('/health', (_req, res) => res.json({ status: 'ok', server: '${name}' }));

  const PORT = process.env.PORT || 3000;
  const httpServer = createServer(app);
  httpServer.listen(PORT, () => {
    console.error(\`MCP server listening on port \${PORT}\`);
  });
`;
  } else {
    code += `  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('MCP server running on stdio');
`;
  }

  code += `}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
`;

  return code;
}

function generateReadme(name, hasHttp, hasStdio) {
  const transports = [];
  if (hasStdio) transports.push('stdio');
  if (hasHttp) transports.push('HTTP');

  return `# ${name}

> MCP Server — generated by [scl339-mcp-server](https://github.com/shuchengle/mcp-server-boilerplate)

An MCP (Model Context Protocol) server providing tools and resources to AI coding assistants like Claude Code, Cursor, and Windsurf.

## Transports

This server supports: **${transports.join(', ')}**

${hasStdio ? `### stdio (default)

The stdio transport communicates with AI coding assistants via standard input/output. This is the standard MCP transport used by Claude Code and similar tools.` : ''}

${hasHttp ? `### HTTP

The HTTP transport exposes an API endpoint for remote access.

Endpoint: \`POST /mcp\`
Health: \`GET /health\`` : ''}

## Getting Started

\`\`\`bash
# Install dependencies
npm install

# Start the server
npm start
\`\`\`

${hasHttp ? `### HTTP Mode

\`\`\`bash
# Configure
cp .env.example .env
# Edit .env with your settings

# Start
npm start
\`\`\`` : ''}

## Available Tools

| Tool   | Description                      | Parameters        |
|--------|----------------------------------|-------------------|
| hello  | A simple hello world tool        | \`name\` (string)   |
| echo   | Echo back the input message      | \`message\` (string) |

## Available Resources

| URI          | Description                    |
|--------------|--------------------------------|
| \`mcp://info\` | Server metadata and version info |

## Configuration

| Variable | Default | Description         |
|----------|---------|---------------------|
| \`PORT\`   | \`3000\`  | HTTP server port (HTTP transport only) |

---

## Related SCL339 Projects

- [scl339-codebase-analyzer](https://github.com/shuchengle/codebase-analyzer) — Analyze your codebase and generate beautiful statistics reports
- [scl339-mcp-server](https://github.com/shuchengle/mcp-server-boilerplate) — This project

## Sponsorship

If you find this project useful, consider sponsoring via Alipay:

**Alipay Account:** 18559219554

Your support helps maintain and improve this project!

## License

MIT © shuchengle
`;
}

function generateEnvExample(hasHttp) {
  let env = `# MCP Server Configuration\n`;
  if (hasHttp) {
    env += `PORT=3000\n`;
  }
  return env;
}
